version: "1.0"

services:
  thescoreserv:
    image: thescoreserv
    build:
      context: ./rushChallenge
      dockerfile: Dockerfile

    env_file:
      - ./.env

    ports:
      - 8080:8080

  thescoreUI:
    image: thescoreui

    build:
      context: ./rush-challengeUI
      dockerfile: Dockerfile

    env_file:
      - ./.env

    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}

    ports:
      - 3000:3000

    depends_on:
      - thescoreserv
